apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: hello-node.local
   http:
     paths:
     - path: /*
       backend:
         serviceName: {{ template "fullname" . }}
         servicePort: {{ .Values.service.externalPort }}